2019-09-12 08:24:38,040 INFO:             errors [in main.py:57]
2019-09-12 08:26:03,535 ERROR:             Exception on /ocr/cnh [POST] [in /usr/local/lib/python3.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2019-09-12 08:27:21,517 INFO:             errors [in main.py:58]
2019-09-12 08:27:40,624 INFO:             errors [in main.py:58]
2019-09-12 08:27:55,473 INFO:             errors [in main.py:59]
2019-09-12 08:31:21,259 INFO:             errors [in main.py:59]
2019-09-12 08:31:41,153 INFO:             errors [in main.py:60]
2019-09-12 08:32:22,636 INFO:             errors [in main.py:60]
2019-09-12 08:32:39,260 INFO:             errors [in main.py:60]
2019-09-12 08:34:10,637 INFO:             errors [in main.py:60]
2019-09-12 08:38:32,046 INFO:             errors [in main.py:50]
2019-09-12 08:41:13,646 INFO:             errors [in main.py:50]
2019-09-12 08:41:21,166 ERROR:             Exception on /v1/ocr/cnh [POST] [in /usr/local/lib/python3.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2019-09-12 08:41:39,999 ERROR:             Exception on /v1/ocr/cnh [POST] [in /usr/local/lib/python3.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2019-09-12 08:42:00,700 INFO:             errors [in main.py:50]
